cienciadedatos/r4ds

.gitignore
README.md
datetimes.Rmd

respecto de chunk en linea 105
modifica el select para generar mismo dataset `vuelos_dt` que en el original
corrige error de compilacion en #2

nota de traduccion en datetimes.rmd

---

model-many.Rmd

Dejé las cosas que me generan más dudas marcadas con: "(TODO: ...)". 
Pendientes:
- definir cómo vamos a redactar que no usamos el dataset `gapminder`, sino una traducción. 
- modificar las citas a otros capítulos cuando estén los títulos en español.
- cambiar el `as.tibble(paises)` que usé cuando usaba el dataset `paises`, si lo cambiamos en el paquete.
- traducir el código cuando se traduzca el dataset `mtcars`.

Traduccion d4tagirl

---

model-many.Rmd

Cambio de mtcars por mtautos.

---

communicate.Rmd

Primera versión sujeta a revisión de la Introducción del capítulo nro. 26: Comunicación

Traducción Introducción Communicate.Rmd

---

program.Rmd
wrangle.Rmd

Traducción de Program. Falta la cambiar  la figura que tiene este capitulo . Falta traducir esa figura.

Traduccion program monica

---

README.md

translate title

---

visualize.Rmd

Implementa los comentarios de los revisores discutidos en el PR [#24](https://github.com/cienciadedatos/r4ds/pull/24), respecto al capítulo visualize.Rmd.
Traducción: @flor14 @mpaulacaldas
Revisión: @ajcanepa  @a-saza

Traducción mpaulacaldas (Related #24)

---

DESCRIPTION
README.md
_output.yaml
wrangle.Rmd

This changes the title in a few places and fixes some syntax so that the outline of the book of properly formatted.

Formatting

---

rmarkdown-workflow.Rmd
rmarkdown.Rmd

@pachamaltese, esta es la versión con los cambios incorporados de los capítulos 27 y 30, ambos traducidos por @julybenitez . Estaban incorporados en el libro, pero en su versión sin revisar.

traducción rmarkdown y rmarkdown-workflow @julybenitez

---

01-intro.Rmd

Traducción de la introducción del libro. Incluye sección adicional acerca del paquete `datos` en el apartado sobre "Prerrequisitos" .

traducción 01-intro.Rmd

---

03-visualize.Rmd
05-transform.Rmd
10-tibble.Rmd
12-tidy.Rmd
15-factors.Rmd
16-datetimes.Rmd
20-vectors.Rmd
23-model-basics.Rmd
25-model-many.Rmd
27-rmarkdown.Rmd
28-communicate-plots.Rmd

Arreglo de detalles en el código de los capítulos 3, 5, 10, 12, 15, 16, 20, 23, 27, 28.

primera revisión código ejercicios y ejemplos

---

15-factors.Rmd

Se agrega argumento a `fct_lump()` para que la etiqueta de _otros valores_ esté en español y no en inglés.

arreglo en el código del capítulo 15: Factores

---

18-pipes.Rmd

Esta es la versión en que se incorporan las sugerencias de quienes revisaron la traducción (la que estaba publicada no los incluía).

traducción capítulo Pipes de @data_datum

---

14-strings.Rmd

Traducción del capítulo sobre cadenas de caracteres. Varios de los ejercicios tuvieron que ser modificados para que funcionaran en español.

traducción capítulo 14 - Strings

---

08-workflow-projects.Rmd

Traducción capítulo "Workflow Projects" hecha en https://github.com/cienciadedatos/r4ds/pull/6.
Este _pull request_ resuelve los conflictos para hacer _merge_.

traducción pamela capítulo Workflow Projects

---

24-model-building.Rmd

Traducción de Fernando Álvarez del capítulo sobre Construcción de Modelos. Resuelve conflictos de https://github.com/cienciadedatos/r4ds/pull/31

traducción Fernando Álvarez capítulo Model Building

---

11-import.Rmd
12-tidy.Rmd
13-relational-data.Rmd
14-strings.Rmd
15-factors.Rmd
16-datetimes.Rmd

Ediciones menores en el texto. Hago _merge_ si es que pasa todos los _checks_.
Lista la sección II :rocket:

copyediting capítulos 11  a 16

---

20-vectors.Rmd
chequear_traduccion.R

Corrigiendo errores ortográficos capítulo 20-vectors.Rmd

Corrigiendo errores ortográficos capítulo 20-vectors.Rmd

---

17-program.Rmd

Cambios menores. Si pasa los _checks_ hago el _merge_ :avocado:

copyediting 17-program.Rmd

---

18-pipes.Rmd

Hago _merge_ si pasa los _checks_ :robot:

copyediting 18-pipes.Rmd

---

20-vectors.Rmd

arregla referencia imágenes capítulo 20 (ahora sí)

---

01-intro.Rmd
03-visualize.Rmd
21-iteration.Rmd
_output.yml

Estoy leyendo el libro completo en mi Kindle, por lo que tuve que hacer algunos cambios para poder generar la versión de libro electrónico, a medida que avance y vaya detectando cosas iré incorporando a las modificaciones a este PR.

pmoracho-changes

---

03-visualize.Rmd

- modifica método de instalación de `datos`
- actualiza funciones deprecadas a partir de ggplot2 versión 3.0
- arregla typos y cosas de formato

actualiza capítulo 3

---

01-intro.Rmd
03-visualize.Rmd
05-transform.Rmd

porque ya volvió a CRAN :package: :tada:

actualiza método de instalación del paquete datos

---

.github/workflows/build_book.yaml

otherwise, new contributions won't render

fix deprecated actions
